name: Build and Deploy

on:
  push:
    tags:
      - bundle@*.*.*

jobs:
  build-and-deploy:
    runs-on: macos-12
    environment: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b # v1.144.0
        with:
          ruby-version: '2.7.6'

      - name: ci/prepare-ios-build
        uses: ./.github/actions/prepare-ios-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::886779261370:role/OIDC_Link--LS-deployment
          role-session-name: ElasticBeanstalkDeployment

      - name: ci/build-ios-bundle
        run: |
          bundle exec fastlane android build_bundle
          bundle exec fastlane ios build_bundle
        working-directory: ./fastlane
